-- MySQL - Servidor Local Schema

CREATE TABLE IF NOT EXISTS registros_ibge (
  id              INT AUTO_INCREMENT  PRIMARY KEY,
  estacao         VARCHAR(50)         NOT NULL,
  ano             VARCHAR(10)         NOT NULL,
  dia_corrido     VARCHAR(10)         NOT NULL,
  url_download    VARCHAR(500)        UNIQUE NOT NULL,
  status_download VARCHAR(20)         NOT NULL DEFAULT 'pendente',
  status_ppp      VARCHAR(20)         NOT NULL DEFAULT 'pendente',
  status_drive    VARCHAR(20)         NOT NULL DEFAULT 'pendente',
  erro_msg        TEXT,
  arquivo_ppp     TEXT,
  criado_em       DATETIME            NOT NULL DEFAULT NOW(),
  atualizado_em   DATETIME            NOT NULL DEFAULT NOW(),
  inicio_execucao DATETIME,
  fim_execucao    DATETIME,
  tempo_execucao  DECIMAL(10,3)
);

CREATE TABLE IF NOT EXISTS resultados_ppp (
  id              INT AUTO_INCREMENT  PRIMARY KEY,
  registro_id     INT                 UNIQUE,
  url_download    VARCHAR(500)        UNIQUE NOT NULL,
  link_zip        TEXT,
  status_ppp      VARCHAR(20),
  processo_em     DATETIME,
  rinex           VARCHAR(100),
  marco           VARCHAR(50),
  inicio          DATETIME,
  fim             DATETIME,
  modo            VARCHAR(50),
  antena          VARCHAR(100),
  altant          DECIMAL(8,3),
  intervalo       DECIMAL(6,2),
  frequencia      VARCHAR(20),
  observacao      VARCHAR(100),
  orbita          VARCHAR(50),
  datum           VARCHAR(100),
  lat             VARCHAR(50),
  lon             VARCHAR(50),
  hgeo            DECIMAL(10,4),
  hnor            DECIMAL(10,4),
  sigma_lat       DECIMAL(8,5),
  sigma_lon       DECIMAL(8,5),
  sigma_hgeo      DECIMAL(8,5),
  utmn            DECIMAL(12,3),
  utme            DECIMAL(12,3),
  mc              INT,
  modelo_geoidal  VARCHAR(100),
  fator_correcao  DECIMAL(8,4),
  incerteza       DECIMAL(8,4),
  criado_em       DATETIME            NOT NULL DEFAULT NOW(),
  FOREIGN KEY (registro_id) REFERENCES registros_ibge(id)
);
