-- Postgres - Supabase Schema

CREATE TABLE IF NOT EXISTS registros_ibge (
  id              SERIAL          PRIMARY KEY,
  estacao         TEXT            NOT NULL,
  ano             TEXT            NOT NULL,
  dia_corrido     TEXT            NOT NULL,
  url_download    TEXT            UNIQUE NOT NULL,
  status_download TEXT            NOT NULL DEFAULT 'pendente',
  status_ppp      TEXT            NOT NULL DEFAULT 'pendente',
  status_drive    TEXT            NOT NULL DEFAULT 'pendente',
  erro_msg        TEXT,
  arquivo_ppp     TEXT,
  criado_em       TIMESTAMP       NOT NULL DEFAULT NOW(),
  atualizado_em   TIMESTAMP       NOT NULL DEFAULT NOW(),
  inicio_execucao TIMESTAMP,
  fim_execucao    TIMESTAMP,
  tempo_execucao  NUMERIC(10,3)
);

CREATE TABLE IF NOT EXISTS resultados_ppp (
  id              SERIAL          PRIMARY KEY,
  registro_id     INT             UNIQUE REFERENCES registros_ibge(id),
  url_download    TEXT            UNIQUE NOT NULL,
  link_zip        TEXT,
  status_ppp      TEXT,
  processo_em     TIMESTAMP,
  rinex           TEXT,
  marco           TEXT,
  inicio          TIMESTAMP,
  fim             TIMESTAMP,
  modo            TEXT,
  antena          TEXT,
  altant          NUMERIC(8,3),
  intervalo       NUMERIC(6,2),
  frequencia      TEXT,
  observacao      TEXT,
  orbita          TEXT,
  datum           TEXT,
  lat             TEXT,
  lon             TEXT,
  hgeo            NUMERIC(10,4),
  hnor            NUMERIC(10,4),
  sigma_lat       NUMERIC(8,5),
  sigma_lon       NUMERIC(8,5),
  sigma_hgeo      NUMERIC(8,5),
  utmn            NUMERIC(12,3),
  utme            NUMERIC(12,3),
  mc              INT,
  modelo_geoidal  TEXT,
  fator_correcao  NUMERIC(8,4),
  incerteza       NUMERIC(8,4),
  criado_em       TIMESTAMP       NOT NULL DEFAULT NOW()
);
